
from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector
# from datetime import date
from PyQt5.QtGui import QPixmap


class Ui_manual_attendance(object):
    def __init__(self, UserName, Subject, Semester):

            self.UserName = UserName
            self.Subject = Subject
            self.Semester = Semester

    def setupUi(self, manual_attendance):
        manual_attendance.setObjectName("manual_attendance")
        manual_attendance.resize(905, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/FaceAttend2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        manual_attendance.setWindowIcon(icon)
        self.grid_layout = QtWidgets.QGridLayout(manual_attendance)
        self.grid_layout.setObjectName("grid_layout")
        self.grid_layout_1 = QtWidgets.QGridLayout()
        self.grid_layout_1.setObjectName("grid_layout_1")
        self.button_back = QtWidgets.QPushButton(manual_attendance)
        self.button_back.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/return.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_back.setIcon(icon1)
        self.button_back.setIconSize(QtCore.QSize(32, 32))
        self.button_back.setFlat(True)
        self.button_back.setObjectName("button_back")
        self.grid_layout_1.addWidget(self.button_back, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.label_manual_attendance = QtWidgets.QLabel(manual_attendance)
        self.label_manual_attendance.setObjectName("label_manual_attendance")
        self.grid_layout_1.addWidget(self.label_manual_attendance, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_spacer = QtWidgets.QLabel(manual_attendance)
        self.label_spacer.setText("")
        self.label_spacer.setObjectName("label_spacer")
        self.grid_layout_1.addWidget(self.label_spacer, 0, 2, 1, 1)
        self.grid_layout.addLayout(self.grid_layout_1, 0, 0, 1, 3)
        self.grid_layout_2 = QtWidgets.QGridLayout()
        self.grid_layout_2.setObjectName("grid_layout_2")
        self.vertical_layout_3 = QtWidgets.QVBoxLayout()
        self.vertical_layout_3.setObjectName("vertical_layout_3")
        self.checkbox_3 = QtWidgets.QCheckBox(manual_attendance)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkbox_3.setIcon(icon2)
        self.checkbox_3.setIconSize(QtCore.QSize(64, 64))
        self.checkbox_3.setObjectName("checkbox_3")
        self.vertical_layout_3.addWidget(self.checkbox_3)
        self.label_3 = QtWidgets.QLabel(manual_attendance)
        self.label_3.setObjectName("label_3")
        self.vertical_layout_3.addWidget(self.label_3)
        self.grid_layout_2.addLayout(self.vertical_layout_3, 0, 4, 1, 1)
        self.vertical_layout_8 = QtWidgets.QVBoxLayout()
        self.vertical_layout_8.setObjectName("vertical_layout_8")
        self.checkbox_8 = QtWidgets.QCheckBox(manual_attendance)
        self.checkbox_8.setIcon(icon2)
        self.checkbox_8.setIconSize(QtCore.QSize(64, 64))
        self.checkbox_8.setObjectName("checkbox_8")
        self.vertical_layout_8.addWidget(self.checkbox_8)
        self.label_8 = QtWidgets.QLabel(manual_attendance)
        self.label_8.setObjectName("label_8")
        self.vertical_layout_8.addWidget(self.label_8)
        self.grid_layout_2.addLayout(self.vertical_layout_8, 2, 4, 1, 1)
        self.vertical_layout_2 = QtWidgets.QVBoxLayout()
        self.vertical_layout_2.setObjectName("vertical_layout_2")
        self.checkbox_2 = QtWidgets.QCheckBox(manual_attendance)
        self.checkbox_2.setIcon(icon2)
        self.checkbox_2.setIconSize(QtCore.QSize(64, 64))
        self.checkbox_2.setObjectName("checkbox_2")
        self.vertical_layout_2.addWidget(self.checkbox_2)
        self.label_2 = QtWidgets.QLabel(manual_attendance)
        self.label_2.setObjectName("label_2")
        self.vertical_layout_2.addWidget(self.label_2)
        self.grid_layout_2.addLayout(self.vertical_layout_2, 0, 2, 1, 1)
        self.vertical_layout_7 = QtWidgets.QVBoxLayout()
        self.vertical_layout_7.setObjectName("vertical_layout_7")
        self.checkbox_7 = QtWidgets.QCheckBox(manual_attendance)
        self.checkbox_7.setIcon(icon2)
        self.checkbox_7.setIconSize(QtCore.QSize(64, 64))
        self.checkbox_7.setObjectName("checkbox_7")
        self.vertical_layout_7.addWidget(self.checkbox_7)
        self.label_7 = QtWidgets.QLabel(manual_attendance)
        self.label_7.setObjectName("label_7")
        self.vertical_layout_7.addWidget(self.label_7)
        self.grid_layout_2.addLayout(self.vertical_layout_7, 2, 2, 1, 1)
        self.vertical_layout_1 = QtWidgets.QVBoxLayout()
        self.vertical_layout_1.setObjectName("vertical_layout_1")
        self.checkbox_1 = QtWidgets.QCheckBox(manual_attendance)
        self.checkbox_1.setIcon(icon2)
        self.checkbox_1.setIconSize(QtCore.QSize(64, 64))
        self.checkbox_1.setObjectName("checkbox_1")
        self.vertical_layout_1.addWidget(self.checkbox_1)
        self.label_1 = QtWidgets.QLabel(manual_attendance)
        self.label_1.setObjectName("label_1")
        self.vertical_layout_1.addWidget(self.label_1)
        self.grid_layout_2.addLayout(self.vertical_layout_1, 0, 0, 1, 1)
        self.vertical_layout_5 = QtWidgets.QVBoxLayout()
        self.vertical_layout_5.setObjectName("vertical_layout_5")
        self.checkbox_5 = QtWidgets.QCheckBox(manual_attendance)
        self.checkbox_5.setIcon(icon2)
        self.checkbox_5.setIconSize(QtCore.QSize(64, 64))
        self.checkbox_5.setObjectName("checkbox_5")
        self.vertical_layout_5.addWidget(self.checkbox_5)
        self.label_5 = QtWidgets.QLabel(manual_attendance)
        self.label_5.setObjectName("label_5")
        self.vertical_layout_5.addWidget(self.label_5)
        self.grid_layout_2.addLayout(self.vertical_layout_5, 0, 8, 1, 1)
        self.v_line_4 = QtWidgets.QFrame(manual_attendance)
        self.v_line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line_4.setObjectName("v_line_4")
        self.grid_layout_2.addWidget(self.v_line_4, 0, 7, 1, 1)
        self.h_line_1 = QtWidgets.QFrame(manual_attendance)
        self.h_line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.h_line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.h_line_1.setObjectName("h_line_1")
        self.grid_layout_2.addWidget(self.h_line_1, 1, 0, 1, 1)
        self.vertical_layout_10 = QtWidgets.QVBoxLayout()
        self.vertical_layout_10.setObjectName("vertical_layout_10")
        self.checkbox_10 = QtWidgets.QCheckBox(manual_attendance)
        self.checkbox_10.setIcon(icon2)
        self.checkbox_10.setIconSize(QtCore.QSize(64, 64))
        self.checkbox_10.setObjectName("checkbox_10")
        self.vertical_layout_10.addWidget(self.checkbox_10)
        self.label_10 = QtWidgets.QLabel(manual_attendance)
        self.label_10.setObjectName("label_10")
        self.vertical_layout_10.addWidget(self.label_10)
        self.grid_layout_2.addLayout(self.vertical_layout_10, 2, 8, 1, 1)
        self.vertical_layout_4 = QtWidgets.QVBoxLayout()
        self.vertical_layout_4.setObjectName("vertical_layout_4")
        self.checkbox_4 = QtWidgets.QCheckBox(manual_attendance)
        self.checkbox_4.setIcon(icon2)
        self.checkbox_4.setIconSize(QtCore.QSize(64, 64))
        self.checkbox_4.setObjectName("checkbox_4")
        self.vertical_layout_4.addWidget(self.checkbox_4)
        self.label_4 = QtWidgets.QLabel(manual_attendance)
        self.label_4.setObjectName("label_4")
        self.vertical_layout_4.addWidget(self.label_4)
        self.grid_layout_2.addLayout(self.vertical_layout_4, 0, 6, 1, 1)
        self.v_line_1 = QtWidgets.QFrame(manual_attendance)
        self.v_line_1.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line_1.setObjectName("v_line_1")
        self.grid_layout_2.addWidget(self.v_line_1, 0, 1, 1, 1)
        self.vertical_layout_9 = QtWidgets.QVBoxLayout()
        self.vertical_layout_9.setObjectName("vertical_layout_9")
        self.checkbox_9 = QtWidgets.QCheckBox(manual_attendance)
        self.checkbox_9.setIcon(icon2)
        self.checkbox_9.setIconSize(QtCore.QSize(64, 64))
        self.checkbox_9.setObjectName("checkbox_9")
        self.vertical_layout_9.addWidget(self.checkbox_9)
        self.label_9 = QtWidgets.QLabel(manual_attendance)
        self.label_9.setObjectName("label_9")
        self.vertical_layout_9.addWidget(self.label_9)
        self.grid_layout_2.addLayout(self.vertical_layout_9, 2, 6, 1, 1)
        self.v_line_5 = QtWidgets.QFrame(manual_attendance)
        self.v_line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line_5.setObjectName("v_line_5")
        self.grid_layout_2.addWidget(self.v_line_5, 2, 1, 1, 1)
        self.vertical_layout_6 = QtWidgets.QVBoxLayout()
        self.vertical_layout_6.setObjectName("vertical_layout_6")
        self.checkbox_6 = QtWidgets.QCheckBox(manual_attendance)
        self.checkbox_6.setIcon(icon2)
        self.checkbox_6.setIconSize(QtCore.QSize(64, 64))
        self.checkbox_6.setObjectName("checkbox_6")
        self.vertical_layout_6.addWidget(self.checkbox_6)
        self.label_6 = QtWidgets.QLabel(manual_attendance)
        self.label_6.setObjectName("label_6")
        self.vertical_layout_6.addWidget(self.label_6)
        self.grid_layout_2.addLayout(self.vertical_layout_6, 2, 0, 1, 1)
        self.v_line_7 = QtWidgets.QFrame(manual_attendance)
        self.v_line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line_7.setObjectName("v_line_7")
        self.grid_layout_2.addWidget(self.v_line_7, 2, 5, 1, 1)
        self.v_line_3 = QtWidgets.QFrame(manual_attendance)
        self.v_line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line_3.setObjectName("v_line_3")
        self.grid_layout_2.addWidget(self.v_line_3, 0, 5, 1, 1)
        self.v_line_6 = QtWidgets.QFrame(manual_attendance)
        self.v_line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line_6.setObjectName("v_line_6")
        self.grid_layout_2.addWidget(self.v_line_6, 2, 3, 1, 1)
        self.v_line_2 = QtWidgets.QFrame(manual_attendance)
        self.v_line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line_2.setObjectName("v_line_2")
        self.grid_layout_2.addWidget(self.v_line_2, 0, 3, 1, 1)
        self.v_line_8 = QtWidgets.QFrame(manual_attendance)
        self.v_line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line_8.setObjectName("v_line_8")
        self.grid_layout_2.addWidget(self.v_line_8, 2, 7, 1, 1)
        self.h_line_2 = QtWidgets.QFrame(manual_attendance)
        self.h_line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.h_line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.h_line_2.setObjectName("h_line_2")
        self.grid_layout_2.addWidget(self.h_line_2, 1, 2, 1, 1)
        self.h_line_3 = QtWidgets.QFrame(manual_attendance)
        self.h_line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.h_line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.h_line_3.setObjectName("h_line_3")
        self.grid_layout_2.addWidget(self.h_line_3, 1, 4, 1, 1)
        self.h_line_4 = QtWidgets.QFrame(manual_attendance)
        self.h_line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.h_line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.h_line_4.setObjectName("h_line_4")
        self.grid_layout_2.addWidget(self.h_line_4, 1, 6, 1, 1)
        self.h_line_5 = QtWidgets.QFrame(manual_attendance)
        self.h_line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.h_line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.h_line_5.setObjectName("h_line_5")
        self.grid_layout_2.addWidget(self.h_line_5, 1, 8, 1, 1)
        self.grid_layout.addLayout(self.grid_layout_2, 10, 0, 2, 3)
        self.button_update = QtWidgets.QPushButton(manual_attendance)
        self.button_update.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("assets/tick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_update.setIcon(icon3)
        self.button_update.setIconSize(QtCore.QSize(32, 32))
        self.button_update.setFlat(False)
        self.button_update.setObjectName("button_update")
        self.grid_layout.addWidget(self.button_update, 13, 0, 1, 3, QtCore.Qt.AlignHCenter)
        self.label_update_icon = QtWidgets.QLabel(manual_attendance)
        self.label_update_icon.setText("")
        self.label_update_icon.setPixmap(QtGui.QPixmap("assets/file.png"))
        self.label_update_icon.setScaledContents(True)
        self.label_update_icon.setObjectName("label_update_icon")
        self.grid_layout.addWidget(self.label_update_icon, 8, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_placeholder = QtWidgets.QLabel(manual_attendance)
        self.label_placeholder.setObjectName("label_placeholder")
        self.grid_layout.addWidget(self.label_placeholder, 9, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)

        self.retranslateUi(manual_attendance)
        self.FuncloadData()
        self.cb[0].stateChanged.connect(lambda: self.FuncChecking(0))
        self.cb[1].stateChanged.connect(lambda: self.FuncChecking(1))
        self.cb[2].stateChanged.connect(lambda: self.FuncChecking(2))
        self.cb[3].stateChanged.connect(lambda: self.FuncChecking(3))
        self.cb[4].stateChanged.connect(lambda: self.FuncChecking(4))

        QtCore.QMetaObject.connectSlotsByName(manual_attendance)
        manual_attendance.setTabOrder(self.checkbox_1, self.checkbox_2)
        manual_attendance.setTabOrder(self.checkbox_2, self.checkbox_3)
        manual_attendance.setTabOrder(self.checkbox_3, self.checkbox_4)
        manual_attendance.setTabOrder(self.checkbox_4, self.checkbox_5)
        manual_attendance.setTabOrder(self.checkbox_5, self.checkbox_6)
        manual_attendance.setTabOrder(self.checkbox_6, self.checkbox_7)
        manual_attendance.setTabOrder(self.checkbox_7, self.checkbox_8)
        manual_attendance.setTabOrder(self.checkbox_8, self.checkbox_9)
        manual_attendance.setTabOrder(self.checkbox_9, self.checkbox_10)
        manual_attendance.setTabOrder(self.checkbox_10, self.button_update)
        manual_attendance.setTabOrder(self.button_update, self.button_back)


    def retranslateUi(self, manual_attendance):
        _translate = QtCore.QCoreApplication.translate
        manual_attendance.setWindowTitle(_translate("manual_attendance", "Manual Attendance"))
        self.label_manual_attendance.setText(_translate("manual_attendance", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#888a85;\">MANUAL ATTENDANCE</span></p></body></html>"))
        self.checkbox_3.setText(_translate("manual_attendance", "CheckBox"))
        self.label_3.setText(_translate("manual_attendance", "TextLabel"))
        self.checkbox_8.setText(_translate("manual_attendance", "CheckBox"))
        self.label_8.setText(_translate("manual_attendance", "TextLabel"))
        self.checkbox_2.setText(_translate("manual_attendance", "CheckBox"))
        self.label_2.setText(_translate("manual_attendance", "TextLabel"))
        self.checkbox_7.setText(_translate("manual_attendance", "CheckBox"))
        self.label_7.setText(_translate("manual_attendance", "TextLabel"))
        self.checkbox_1.setText(_translate("manual_attendance", "CheckBox"))
        self.label_1.setText(_translate("manual_attendance", "TextLabel"))
        self.checkbox_5.setText(_translate("manual_attendance", "CheckBox"))
        self.label_5.setText(_translate("manual_attendance", "TextLabel"))
        self.checkbox_10.setText(_translate("manual_attendance", "CheckBox"))
        self.label_10.setText(_translate("manual_attendance", "TextLabel"))
        self.checkbox_4.setText(_translate("manual_attendance", "CheckBox"))
        self.label_4.setText(_translate("manual_attendance", "TextLabel"))
        self.checkbox_9.setText(_translate("manual_attendance", "CheckBox"))
        self.label_9.setText(_translate("manual_attendance", "TextLabel"))
        self.checkbox_6.setText(_translate("manual_attendance", "CheckBox"))
        self.label_6.setText(_translate("manual_attendance", "TextLabel"))
        self.label_placeholder.setText(_translate("manual_attendance", "Check or uncheck the boxes to change the status of the attendance record of the student:"))
        self.cb = [self.checkbox_1, self.checkbox_2, self.checkbox_3, self.checkbox_4, self.checkbox_5, self.checkbox_6,
                   self.checkbox_7, self.checkbox_8, self.checkbox_9, self.checkbox_10]
        # self.pixx = [self.icon1, self.icon2, self.icon4, self.icon5, self.icon6, self.icon7, self.icon8, self.icon9,
        #              self.icon10]
        # # self.pic1, self.pic2, self.pic3, self.pic4, self.pic5, self.pic6, self.pic7, self.pic8, self.pic9,self.pic10]
        self.rollarr = [self.label_1,self.label_2, self.label_3, self.label_4, self.label_5, self.label_6,self.label_7, self.label_8,self.label_9,self.label_10]
        self.attendance = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        self.vertical = [self.vertical_layout_1,self.vertical_layout_2,self.vertical_layout_3,self.vertical_layout_4,self.vertical_layout_5,self.vertical_layout_6,self.vertical_layout_7,self.vertical_layout_8,self.vertical_layout_9,self.vertical_layout_10]
    def FuncloadData(self):
        rollarr = ["roll1","roll2","roll3","roll4","roll5","roll6","roll7","roll8","roll9","roll10"]
        mydb = mysql.connector.connect(
            host="localhost",
            user="root",
            database="collegeattend",
            passwd=""
        )
        mycursor = mydb.cursor()
        mycursor.execute("""SELECT rollnum,name,pic FROM studentdetails WHERE  semester = %s order by rollnum""",(self.Semester,))
        myresult = mycursor.fetchall()
        if myresult is None:
            print("err")
        else:
            i = 0
            pixmap1 = []
            namearr = []
            for row in myresult:
                pixmap1.append(QPixmap("pic/"+row[2]))
                self.icon4 = QtGui.QIcon()
                self.icon4.addPixmap(pixmap1[i], QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.cb[i].setIcon(self.icon4)
                self.cb[i].setIconSize(QtCore.QSize(51, 51))
                self.vertical[i].addWidget(self.cb[i])
                rn = row[0]
                nm = row[1]
                namearr.append(rn+'. '+nm)
                print(namearr[i])
                self.rollarr[i].setText(namearr[i])
                self.vertical[i].addWidget(self.rollarr[i])
                self.grid_layout_2.addLayout(self.vertical[i], 0, 0, 1, 1)
                print(self.rollarr[i].text())
                i = i + 1

            # self.icon4 = QtGui.QIcon()
            # self.icon4.addPixmap(QtGui.QPixmap("assets/blank.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            # self.cb[i].setIcon(self.icon4)
            # # self.icon4.addPixmap(QtGui.QPixmap("pic/"+pixmap1[i]), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            # self.cb[i].setIcon(self.icon4)
            # self.pixx[i].setPixmap(pixmap1[i])



        # self.pic1.setPixmap(pixmap1[0])
        # self.pic2.setPixmap(pixmap1[1])
        # self.pic3.setPixmap(pixmap1[2])
        # self.pic4.setPixmap(pixmap1[3])
        # self.pic5.setPixmap(pixmap1[4])
        # self.pic6.setPixmap(pixmap1[5])
        # self.pic7.setPixmap(pixmap1[6])
        # self.pic8.setPixmap(pixmap1[7])
        # self.pic9.setPixmap(pixmap1[8])
        # self.pic10.setPixmap(pixmap1[9])

        # self.roll1.setText(namearr[0])
        # self.roll2.setText(namearr[1])
        # self.roll3.setText(namearr[2])
        # self.roll4.setText(namearr[3])
        # self.roll5.setText(namearr[4])
        print(i)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    manual_attendance = QtWidgets.QWidget()
    ui = Ui_manual_attendance()
    ui.setupUi(manual_attendance)
    manual_attendance.show()
    sys._excepthook = sys.excepthook


    def my_exception_hook(exctype, value, traceback):
        # Print the error and traceback
        print(exctype, value, traceback)
        # Call the normal Exception hook after
        sys._excepthook(exctype, value, traceback)
        sys.exit(1)


    # Set the exception hook to our wrapping function
    sys.excepthook = my_exception_hook
    sys.exit(app.exec_())
#
#
#
#
# from PyQt5 import QtCore, QtGui, QtWidgets
# from PyQt5.QtGui import QIcon, QPixmap
#
# class Ui_manual_attendance(object):
#     def __init__(self,UserName,Subject,Semester):
#         self.UserName = UserName
#         self.Subject = Subject
#         self.Semester = Semester
#
#     def setupUi(self, manual_attendance):
#         manual_attendance.setObjectName("manual_attendance")
#         manual_attendance.resize(905, 480)
#         icon = QtGui.QIcon()
#         icon.addPixmap(QtGui.QPixmap("assets/FaceAttend2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#         manual_attendance.setWindowIcon(icon)
#         self.grid_layout = QtWidgets.QGridLayout(manual_attendance)
#         self.grid_layout.setObjectName("grid_layout")
#         self.grid_layout_1 = QtWidgets.QGridLayout()
#         self.grid_layout_1.setObjectName("grid_layout_1")
#         self.button_back = QtWidgets.QPushButton(manual_attendance)
#         self.button_back.setText("")
#         icon1 = QtGui.QIcon()
#         icon1.addPixmap(QtGui.QPixmap("assets/return.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#         self.button_back.setIcon(icon1)
#         self.button_back.setIconSize(QtCore.QSize(32, 32))
#         self.button_back.setFlat(True)
#         self.button_back.setObjectName("button_back")
#         self.grid_layout_1.addWidget(self.button_back, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
#         self.label_manual_attendance = QtWidgets.QLabel(manual_attendance)
#         self.label_manual_attendance.setObjectName("label_manual_attendance")
#         self.grid_layout_1.addWidget(self.label_manual_attendance, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
#         self.label_spacer = QtWidgets.QLabel(manual_attendance)
#         self.label_spacer.setText("")
#         self.label_spacer.setObjectName("label_spacer")
#         self.grid_layout_1.addWidget(self.label_spacer, 0, 2, 1, 1)
#         self.grid_layout.addLayout(self.grid_layout_1, 0, 0, 1, 3)
#         self.grid_layout_2 = QtWidgets.QGridLayout()
#         self.grid_layout_2.setObjectName("grid_layout_2")
#         self.vertical_layout_3 = QtWidgets.QVBoxLayout()
#         self.vertical_layout_3.setObjectName("vertical_layout_3")
#         self.checkbox_3 = QtWidgets.QCheckBox(manual_attendance)
#         icon2 = QtGui.QIcon()
#         icon2.addPixmap(QtGui.QPixmap("assets/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#         self.checkbox_3.setIcon(icon2)
#         self.checkbox_3.setIconSize(QtCore.QSize(64, 64))
#         self.checkbox_3.setObjectName("checkbox_3")
#         self.vertical_layout_3.addWidget(self.checkbox_3)
#         self.label_3 = QtWidgets.QLabel(manual_attendance)
#         self.label_3.setObjectName("label_3")
#         self.vertical_layout_3.addWidget(self.label_3)
#         self.grid_layout_2.addLayout(self.vertical_layout_3, 0, 4, 1, 1)
#         self.vertical_layout_8 = QtWidgets.QVBoxLayout()
#         self.vertical_layout_8.setObjectName("vertical_layout_8")
#         self.checkbox_8 = QtWidgets.QCheckBox(manual_attendance)
#         self.checkbox_8.setIcon(icon2)
#         self.checkbox_8.setIconSize(QtCore.QSize(64, 64))
#         self.checkbox_8.setObjectName("checkbox_8")
#         self.vertical_layout_8.addWidget(self.checkbox_8)
#         self.label_8 = QtWidgets.QLabel(manual_attendance)
#         self.label_8.setObjectName("label_8")
#         self.vertical_layout_8.addWidget(self.label_8)
#         self.grid_layout_2.addLayout(self.vertical_layout_8, 2, 4, 1, 1)
#         self.vertical_layout_2 = QtWidgets.QVBoxLayout()
#         self.vertical_layout_2.setObjectName("vertical_layout_2")
#         self.checkbox_2 = QtWidgets.QCheckBox(manual_attendance)
#         self.checkbox_2.setIcon(icon2)
#         self.checkbox_2.setIconSize(QtCore.QSize(64, 64))
#         self.checkbox_2.setObjectName("checkbox_2")
#         self.vertical_layout_2.addWidget(self.checkbox_2)
#         self.label_2 = QtWidgets.QLabel(manual_attendance)
#         self.label_2.setObjectName("label_2")
#         self.vertical_layout_2.addWidget(self.label_2)
#         self.grid_layout_2.addLayout(self.vertical_layout_2, 0, 2, 1, 1)
#         self.vertical_layout_7 = QtWidgets.QVBoxLayout()
#         self.vertical_layout_7.setObjectName("vertical_layout_7")
#         self.checkbox_7 = QtWidgets.QCheckBox(manual_attendance)
#         self.checkbox_7.setIcon(icon2)
#         self.checkbox_7.setIconSize(QtCore.QSize(64, 64))
#         self.checkbox_7.setObjectName("checkbox_7")
#         self.vertical_layout_7.addWidget(self.checkbox_7)
#         self.label_7 = QtWidgets.QLabel(manual_attendance)
#         self.label_7.setObjectName("label_7")
#         self.vertical_layout_7.addWidget(self.label_7)
#         self.grid_layout_2.addLayout(self.vertical_layout_7, 2, 2, 1, 1)
#         self.vertical_layout_1 = QtWidgets.QVBoxLayout()
#         self.vertical_layout_1.setObjectName("vertical_layout_1")
#         self.checkbox_1 = QtWidgets.QCheckBox(manual_attendance)
#         self.checkbox_1.setIcon(icon2)
#         self.checkbox_1.setIconSize(QtCore.QSize(64, 64))
#         self.checkbox_1.setObjectName("checkbox_1")
#         self.vertical_layout_1.addWidget(self.checkbox_1)
#         self.label_1 = QtWidgets.QLabel(manual_attendance)
#         self.label_1.setObjectName("label_1")
#         self.vertical_layout_1.addWidget(self.label_1)
#         self.grid_layout_2.addLayout(self.vertical_layout_1, 0, 0, 1, 1)
#         self.vertical_layout_5 = QtWidgets.QVBoxLayout()
#         self.vertical_layout_5.setObjectName("vertical_layout_5")
#         self.checkbox_5 = QtWidgets.QCheckBox(manual_attendance)
#         self.checkbox_5.setIcon(icon2)
#         self.checkbox_5.setIconSize(QtCore.QSize(64, 64))
#         self.checkbox_5.setObjectName("checkbox_5")
#         self.vertical_layout_5.addWidget(self.checkbox_5)
#         self.label_5 = QtWidgets.QLabel(manual_attendance)
#         self.label_5.setObjectName("label_5")
#         self.vertical_layout_5.addWidget(self.label_5)
#         self.grid_layout_2.addLayout(self.vertical_layout_5, 0, 8, 1, 1)
#         self.v_line_4 = QtWidgets.QFrame(manual_attendance)
#         self.v_line_4.setFrameShape(QtWidgets.QFrame.VLine)
#         self.v_line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.v_line_4.setObjectName("v_line_4")
#         self.grid_layout_2.addWidget(self.v_line_4, 0, 7, 1, 1)
#         self.h_line_1 = QtWidgets.QFrame(manual_attendance)
#         self.h_line_1.setFrameShape(QtWidgets.QFrame.HLine)
#         self.h_line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.h_line_1.setObjectName("h_line_1")
#         self.grid_layout_2.addWidget(self.h_line_1, 1, 0, 1, 1)
#         self.vertical_layout_10 = QtWidgets.QVBoxLayout()
#         self.vertical_layout_10.setObjectName("vertical_layout_10")
#         self.checkbox_10 = QtWidgets.QCheckBox(manual_attendance)
#         self.checkbox_10.setIcon(icon2)
#         self.checkbox_10.setIconSize(QtCore.QSize(64, 64))
#         self.checkbox_10.setObjectName("checkbox_10")
#         self.vertical_layout_10.addWidget(self.checkbox_10)
#         self.label_10 = QtWidgets.QLabel(manual_attendance)
#         self.label_10.setObjectName("label_10")
#         self.vertical_layout_10.addWidget(self.label_10)
#         self.grid_layout_2.addLayout(self.vertical_layout_10, 2, 8, 1, 1)
#         self.vertical_layout_4 = QtWidgets.QVBoxLayout()
#         self.vertical_layout_4.setObjectName("vertical_layout_4")
#         self.checkbox_4 = QtWidgets.QCheckBox(manual_attendance)
#         self.checkbox_4.setIcon(icon2)
#         self.checkbox_4.setIconSize(QtCore.QSize(64, 64))
#         self.checkbox_4.setObjectName("checkbox_4")
#         self.vertical_layout_4.addWidget(self.checkbox_4)
#         self.label_4 = QtWidgets.QLabel(manual_attendance)
#         self.label_4.setObjectName("label_4")
#         self.vertical_layout_4.addWidget(self.label_4)
#         self.grid_layout_2.addLayout(self.vertical_layout_4, 0, 6, 1, 1)
#         self.v_line_1 = QtWidgets.QFrame(manual_attendance)
#         self.v_line_1.setFrameShape(QtWidgets.QFrame.VLine)
#         self.v_line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.v_line_1.setObjectName("v_line_1")
#         self.grid_layout_2.addWidget(self.v_line_1, 0, 1, 1, 1)
#         self.vertical_layout_9 = QtWidgets.QVBoxLayout()
#         self.vertical_layout_9.setObjectName("vertical_layout_9")
#         self.checkbox_9 = QtWidgets.QCheckBox(manual_attendance)
#         self.checkbox_9.setIcon(icon2)
#         self.checkbox_9.setIconSize(QtCore.QSize(64, 64))
#         self.checkbox_9.setObjectName("checkbox_9")
#         self.vertical_layout_9.addWidget(self.checkbox_9)
#         self.label_9 = QtWidgets.QLabel(manual_attendance)
#         self.label_9.setObjectName("label_9")
#         self.vertical_layout_9.addWidget(self.label_9)
#         self.grid_layout_2.addLayout(self.vertical_layout_9, 2, 6, 1, 1)
#         self.v_line_5 = QtWidgets.QFrame(manual_attendance)
#         self.v_line_5.setFrameShape(QtWidgets.QFrame.VLine)
#         self.v_line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.v_line_5.setObjectName("v_line_5")
#         self.grid_layout_2.addWidget(self.v_line_5, 2, 1, 1, 1)
#         self.vertical_layout_6 = QtWidgets.QVBoxLayout()
#         self.vertical_layout_6.setObjectName("vertical_layout_6")
#         self.checkbox_6 = QtWidgets.QCheckBox(manual_attendance)
#         self.checkbox_6.setIcon(icon2)
#         self.checkbox_6.setIconSize(QtCore.QSize(64, 64))
#         self.checkbox_6.setObjectName("checkbox_6")
#         self.vertical_layout_6.addWidget(self.checkbox_6)
#         self.label_6 = QtWidgets.QLabel(manual_attendance)
#         self.label_6.setObjectName("label_6")
#         self.vertical_layout_6.addWidget(self.label_6)
#         self.grid_layout_2.addLayout(self.vertical_layout_6, 2, 0, 1, 1)
#         self.v_line_7 = QtWidgets.QFrame(manual_attendance)
#         self.v_line_7.setFrameShape(QtWidgets.QFrame.VLine)
#         self.v_line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.v_line_7.setObjectName("v_line_7")
#         self.grid_layout_2.addWidget(self.v_line_7, 2, 5, 1, 1)
#         self.v_line_3 = QtWidgets.QFrame(manual_attendance)
#         self.v_line_3.setFrameShape(QtWidgets.QFrame.VLine)
#         self.v_line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.v_line_3.setObjectName("v_line_3")
#         self.grid_layout_2.addWidget(self.v_line_3, 0, 5, 1, 1)
#         self.v_line_6 = QtWidgets.QFrame(manual_attendance)
#         self.v_line_6.setFrameShape(QtWidgets.QFrame.VLine)
#         self.v_line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.v_line_6.setObjectName("v_line_6")
#         self.grid_layout_2.addWidget(self.v_line_6, 2, 3, 1, 1)
#         self.v_line_2 = QtWidgets.QFrame(manual_attendance)
#         self.v_line_2.setFrameShape(QtWidgets.QFrame.VLine)
#         self.v_line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.v_line_2.setObjectName("v_line_2")
#         self.grid_layout_2.addWidget(self.v_line_2, 0, 3, 1, 1)
#         self.v_line_8 = QtWidgets.QFrame(manual_attendance)
#         self.v_line_8.setFrameShape(QtWidgets.QFrame.VLine)
#         self.v_line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.v_line_8.setObjectName("v_line_8")
#         self.grid_layout_2.addWidget(self.v_line_8, 2, 7, 1, 1)
#         self.h_line_2 = QtWidgets.QFrame(manual_attendance)
#         self.h_line_2.setFrameShape(QtWidgets.QFrame.HLine)
#         self.h_line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.h_line_2.setObjectName("h_line_2")
#         self.grid_layout_2.addWidget(self.h_line_2, 1, 2, 1, 1)
#         self.h_line_3 = QtWidgets.QFrame(manual_attendance)
#         self.h_line_3.setFrameShape(QtWidgets.QFrame.HLine)
#         self.h_line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.h_line_3.setObjectName("h_line_3")
#         self.grid_layout_2.addWidget(self.h_line_3, 1, 4, 1, 1)
#         self.h_line_4 = QtWidgets.QFrame(manual_attendance)
#         self.h_line_4.setFrameShape(QtWidgets.QFrame.HLine)
#         self.h_line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.h_line_4.setObjectName("h_line_4")
#         self.grid_layout_2.addWidget(self.h_line_4, 1, 6, 1, 1)
#         self.h_line_5 = QtWidgets.QFrame(manual_attendance)
#         self.h_line_5.setFrameShape(QtWidgets.QFrame.HLine)
#         self.h_line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.h_line_5.setObjectName("h_line_5")
#         self.grid_layout_2.addWidget(self.h_line_5, 1, 8, 1, 1)
#         self.grid_layout.addLayout(self.grid_layout_2, 10, 0, 2, 3)
#         self.button_update = QtWidgets.QPushButton(manual_attendance)
#         self.button_update.setText("")
#         icon3 = QtGui.QIcon()
#         icon3.addPixmap(QtGui.QPixmap("assets/tick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#         self.button_update.setIcon(icon3)
#         self.button_update.setIconSize(QtCore.QSize(32, 32))
#         self.button_update.setFlat(False)
#         self.button_update.setObjectName("button_update")
#         self.grid_layout.addWidget(self.button_update, 13, 0, 1, 3, QtCore.Qt.AlignHCenter)
#         self.label_update_icon = QtWidgets.QLabel(manual_attendance)
#         self.label_update_icon.setText("")
#         self.label_update_icon.setPixmap(QtGui.QPixmap("assets/file.png"))
#         self.label_update_icon.setScaledContents(True)
#         self.label_update_icon.setObjectName("label_update_icon")
#         self.grid_layout.addWidget(self.label_update_icon, 8, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
#         self.label_placeholder = QtWidgets.QLabel(manual_attendance)
#         self.label_placeholder.setObjectName("label_placeholder")
#         self.grid_layout.addWidget(self.label_placeholder, 9, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
#         # self.icon4 = QtGui.QIcon()
#         self.retranslateUi(manual_attendance)
#         QtCore.QMetaObject.connectSlotsByName(manual_attendance)
#         manual_attendance.setTabOrder(self.checkbox_1, self.checkbox_2)
#         manual_attendance.setTabOrder(self.checkbox_2, self.checkbox_3)
#         manual_attendance.setTabOrder(self.checkbox_3, self.checkbox_4)
#         manual_attendance.setTabOrder(self.checkbox_4, self.checkbox_5)
#         manual_attendance.setTabOrder(self.checkbox_5, self.checkbox_6)
#         manual_attendance.setTabOrder(self.checkbox_6, self.checkbox_7)
#         manual_attendance.setTabOrder(self.checkbox_7, self.checkbox_8)
#         manual_attendance.setTabOrder(self.checkbox_8, self.checkbox_9)
#         manual_attendance.setTabOrder(self.checkbox_9, self.checkbox_10)
#         manual_attendance.setTabOrder(self.checkbox_10, self.button_update)
#         manual_attendance.setTabOrder(self.button_update, self.button_back)
#         # self.FuncloadData()
#         # self.cb[0].stateChanged.connect(lambda: self.FuncChecking(0))
#         # self.cb[1].stateChanged.connect(lambda: self.FuncChecking(1))
#         # self.cb[2].stateChanged.connect(lambda: self.FuncChecking(2))
#         # self.cb[3].stateChanged.connect(lambda: self.FuncChecking(3))
#         # self.cb[4].stateChanged.connect(lambda: self.FuncChecking(4))
#
#     def retranslateUi(self, manual_attendance):
#         _translate = QtCore.QCoreApplication.translate
#         manual_attendance.setWindowTitle(_translate("manual_attendance", "Manual Attendance"))
#         self.label_manual_attendance.setText(_translate("manual_attendance", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#888a85;\">MANUAL ATTENDANCE</span></p></body></html>"))
#         self.checkbox_3.setText(_translate("manual_attendance", "CheckBox"))
#         self.label_3.setText(_translate("manual_attendance", "TextLabel"))
#         self.checkbox_8.setText(_translate("manual_attendance", "CheckBox"))
#         self.label_8.setText(_translate("manual_attendance", "TextLabel"))
#         self.checkbox_2.setText(_translate("manual_attendance", "CheckBox"))
#         self.label_2.setText(_translate("manual_attendance", "TextLabel"))
#         self.checkbox_7.setText(_translate("manual_attendance", "CheckBox"))
#         self.label_7.setText(_translate("manual_attendance", "TextLabel"))
#         self.checkbox_1.setText(_translate("manual_attendance", "CheckBox"))
#         self.label_1.setText(_translate("manual_attendance", "TextLabel"))
#         self.checkbox_5.setText(_translate("manual_attendance", "CheckBox"))
#         self.label_5.setText(_translate("manual_attendance", "TextLabel"))
#         self.checkbox_10.setText(_translate("manual_attendance", "CheckBox"))
#         self.label_10.setText(_translate("manual_attendance", "TextLabel"))
#         self.checkbox_4.setText(_translate("manual_attendance", "CheckBox"))
#         self.label_4.setText(_translate("manual_attendance", "TextLabel"))
#         self.checkbox_9.setText(_translate("manual_attendance", "CheckBox"))
#         self.label_9.setText(_translate("manual_attendance", "TextLabel"))
#         self.checkbox_6.setText(_translate("manual_attendance", "CheckBox"))
#         self.label_6.setText(_translate("manual_attendance", "TextLabel"))
#         self.label_placeholder.setText(_translate("manual_attendance", "Check or uncheck the boxes to change the status of the attendance record of the student:"))
#         # self.cb = [self.checkbox_1, self.checkbox_2, self.checkbox_3, self.checkbox_4, self.checkbox_5, self.checkbox_6, self.checkbox_7, self.checkbox_8, self.checkbox_9, self.checkbox_10]
#         # # self.pixx = [self.pic1, self.pic2, self.pic3, self.pic4, self.pic5, self.pic6, self.pic7, self.pic8, self.pic9,self.pic10]
#         # self.rollarr = [self.label_1, self.label_2, self.label_3, self.label_4, self.label_5, self.label_6, self.label_7, self.label_8,self.label_9, self.label_10]
#         # self.attendance = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
#
#
#
#     # def FuncloadData(self):
#     #     rollarr = ["roll1","roll2","roll3","roll4","roll5","roll6","roll7","roll8","roll9","roll10"]
#     #     mydb = mysql.connector.connect(
#     #         host="localhost",
#     #         user="root",
#     #         passwd=""
#     #     )
#     #     mycursor = mydb.cursor()
#     #     mycursor.execute("""SELECT rollnum,name,pic FROM collegeattend.studentdetails WHERE  semester = %s order by rollnum""",(self.Semester,))
#     #     myresult = mycursor.fetchall()
#     #     i = 0
#     #     pixmap1 = []
#     #     namearr = []
#     #     for row in myresult:
#     #         pixmap1.append(row[2])
#     #         rn = row[0]
#     #         nm = row[1]
#     #         namearr.append(rn+'. '+nm)
#     #         # self.icon4.addPixmap(QtGui.QPixmap("pic/"+pixmap1[i]), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#     #         # self.cb[i].setIcon(self.icon4)
#     #         # self.pixx[i].setPixmap(pixmap1[i])
#     #         self.rollarr[i].setText(namearr[i])
#     #         i = i + 1
#     #
#     #     # self.pic1.setPixmap(pixmap1[0])
#     #     # self.pic2.setPixmap(pixmap1[1])
#     #     # self.pic3.setPixmap(pixmap1[2])
#     #     # self.pic4.setPixmap(pixmap1[3])
#     #     # self.pic5.setPixmap(pixmap1[4])
#     #     # self.pic6.setPixmap(pixmap1[5])
#     #     # self.pic7.setPixmap(pixmap1[6])
#     #     # self.pic8.setPixmap(pixmap1[7])
#     #     # self.pic9.setPixmap(pixmap1[8])
#     #     # self.pic10.setPixmap(pixmap1[9])
#     #
#     #     # self.roll1.setText(namearr[0])
#     #     # self.roll2.setText(namearr[1])
#     #     # self.roll3.setText(namearr[2])
#     #     # self.roll4.setText(namearr[3])
#     #     # self.roll5.setText(namearr[4])
#     #     print(i)
#     #
#     # def FuncChecking(self,x):
#     #         if  self.cb[x].isChecked() == True:
#     #             self.cb[x].setText("Is Present")
#     #             self.cb[x].setStyleSheet("color: Green")
#     #             self.attendance[x] = 1
#     #         else:
#     #             self.cb[x].setText("Is Absent")
#     #             self.cb[x].setStyleSheet("color: red")
#     #             self.attendance[x] = 0
#     #
#     # def takingAttend(self):
#     #     today = date.today()
#     #     self.attendance[10] = today
#     #     # print("Today's date:", self.attendance[10])
#     #     # print(self.sub)
#     #     # for j in range(11):
#     #     #     print(self.attendance[j])
#     #     try:
#     #         connection = mysql.connector.connect(host='localhost',
#     #                                              database='collegeattend',
#     #                                              user='root',
#     #                                              password='')
#     #         cursor = connection.cursor()
#     #         string = "(`1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `classdate`)"
#     #         tab = "`" + str(self.Subject) + "`" + string
#     #         print(tab)
#     #         cursor.execute("INSERT INTO "+ str(tab) +" VALUES (%s, %s, %s, %s,%s, %s, %s, %s,%s, %s, %s)",(self.attendance[0],self.attendance[1],self.attendance[2],self.attendance[3],self.attendance[4],self.attendance[5],self.attendance[6],self.attendance[7],self.attendance[8],self.attendance[9],self.attendance[10],))
#     #         connection.commit()
#     #
#     #
#     #
#     #         print("Record inserted successfully into "+ str(tab) + "table")
#     #
#     #     except mysql.connector.Error as error:
#     #         print("Failed to insert into MySQL table {}".format(error))
#     #
#     #     finally:
#     #         if (connection.is_connected()):
#     #             cursor.close()
#     #             connection.close()
#     #             print("MySQL connection is closed")
#
# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     manual_attendance = QtWidgets.QWidget()
#     ui = Ui_manual_attendance()
#     ui.setupUi(manual_attendance)
#     manual_attendance.show()
#     sys._excepthook = sys.excepthook
#
#
#     def my_exception_hook(exctype, value, traceback):
#         # Print the error and traceback
#         print(exctype, value, traceback)
#         # Call the normal Exception hook after
#         sys._excepthook(exctype, value, traceback)
#         sys.exit(1)
#
#
#     # Set the exception hook to our wrapping function
#     sys.excepthook = my_exception_hook
#     sys.exit(app.exec_())
