# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manual_attendance.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_manual_attendance(object):
    def setupUi(self, manual_attendance):
        manual_attendance.setObjectName("manual_attendance")
        manual_attendance.resize(720, 500)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/FaceAttend2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        manual_attendance.setWindowIcon(icon)
        self.grid_layout = QtWidgets.QGridLayout(manual_attendance)
        self.grid_layout.setObjectName("grid_layout")
        self.grid_layout_1 = QtWidgets.QGridLayout()
        self.grid_layout_1.setObjectName("grid_layout_1")
        self.button_back = QtWidgets.QPushButton(manual_attendance)
        self.button_back.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/return.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_back.setIcon(icon1)
        self.button_back.setIconSize(QtCore.QSize(32, 32))
        self.button_back.setFlat(True)
        self.button_back.setObjectName("button_back")
        self.grid_layout_1.addWidget(self.button_back, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.label_manual_attendance = QtWidgets.QLabel(manual_attendance)
        self.label_manual_attendance.setObjectName("label_manual_attendance")
        self.grid_layout_1.addWidget(self.label_manual_attendance, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_spacer = QtWidgets.QLabel(manual_attendance)
        self.label_spacer.setText("")
        self.label_spacer.setObjectName("label_spacer")
        self.grid_layout_1.addWidget(self.label_spacer, 0, 2, 1, 1)
        self.grid_layout.addLayout(self.grid_layout_1, 0, 0, 1, 3)
        self.grid_layout_2 = QtWidgets.QGridLayout()
        self.grid_layout_2.setObjectName("grid_layout_2")
        self.vertical_layout_3 = QtWidgets.QVBoxLayout()
        self.vertical_layout_3.setObjectName("vertical_layout_3")
        self.label_picture_3 = QtWidgets.QLabel(manual_attendance)
        self.label_picture_3.setText("")
        self.label_picture_3.setPixmap(QtGui.QPixmap("assets/user.png"))
        self.label_picture_3.setObjectName("label_picture_3")
        self.vertical_layout_3.addWidget(self.label_picture_3, 0, QtCore.Qt.AlignHCenter)
        self.checkbox_3 = QtWidgets.QCheckBox(manual_attendance)
        self.checkbox_3.setIconSize(QtCore.QSize(64, 64))
        self.checkbox_3.setObjectName("checkbox_3")
        self.vertical_layout_3.addWidget(self.checkbox_3, 0, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(manual_attendance)
        self.label_3.setObjectName("label_3")
        self.vertical_layout_3.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.grid_layout_2.addLayout(self.vertical_layout_3, 0, 4, 1, 1)
        self.vertical_layout_8 = QtWidgets.QVBoxLayout()
        self.vertical_layout_8.setObjectName("vertical_layout_8")
        self.label_picture_8 = QtWidgets.QLabel(manual_attendance)
        self.label_picture_8.setText("")
        self.label_picture_8.setPixmap(QtGui.QPixmap("assets/user.png"))
        self.label_picture_8.setObjectName("label_picture_8")
        self.vertical_layout_8.addWidget(self.label_picture_8, 0, QtCore.Qt.AlignHCenter)
        self.checkbox_8 = QtWidgets.QCheckBox(manual_attendance)
        self.checkbox_8.setIconSize(QtCore.QSize(64, 64))
        self.checkbox_8.setObjectName("checkbox_8")
        self.vertical_layout_8.addWidget(self.checkbox_8, 0, QtCore.Qt.AlignHCenter)
        self.label_8 = QtWidgets.QLabel(manual_attendance)
        self.label_8.setObjectName("label_8")
        self.vertical_layout_8.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.grid_layout_2.addLayout(self.vertical_layout_8, 2, 4, 1, 1)
        self.vertical_layout_2 = QtWidgets.QVBoxLayout()
        self.vertical_layout_2.setObjectName("vertical_layout_2")
        self.label_picture_2 = QtWidgets.QLabel(manual_attendance)
        self.label_picture_2.setText("")
        self.label_picture_2.setPixmap(QtGui.QPixmap("assets/user.png"))
        self.label_picture_2.setObjectName("label_picture_2")
        self.vertical_layout_2.addWidget(self.label_picture_2, 0, QtCore.Qt.AlignHCenter)
        self.checkbox_2 = QtWidgets.QCheckBox(manual_attendance)
        self.checkbox_2.setIconSize(QtCore.QSize(64, 64))
        self.checkbox_2.setObjectName("checkbox_2")
        self.vertical_layout_2.addWidget(self.checkbox_2, 0, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(manual_attendance)
        self.label_2.setObjectName("label_2")
        self.vertical_layout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.grid_layout_2.addLayout(self.vertical_layout_2, 0, 2, 1, 1)
        self.vertical_layout_7 = QtWidgets.QVBoxLayout()
        self.vertical_layout_7.setObjectName("vertical_layout_7")
        self.label_picture_7 = QtWidgets.QLabel(manual_attendance)
        self.label_picture_7.setText("")
        self.label_picture_7.setPixmap(QtGui.QPixmap("assets/user.png"))
        self.label_picture_7.setObjectName("label_picture_7")
        self.vertical_layout_7.addWidget(self.label_picture_7, 0, QtCore.Qt.AlignHCenter)
        self.checkbox_7 = QtWidgets.QCheckBox(manual_attendance)
        self.checkbox_7.setIconSize(QtCore.QSize(64, 64))
        self.checkbox_7.setObjectName("checkbox_7")
        self.vertical_layout_7.addWidget(self.checkbox_7, 0, QtCore.Qt.AlignHCenter)
        self.label_7 = QtWidgets.QLabel(manual_attendance)
        self.label_7.setObjectName("label_7")
        self.vertical_layout_7.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter)
        self.grid_layout_2.addLayout(self.vertical_layout_7, 2, 2, 1, 1)
        self.vertical_layout_1 = QtWidgets.QVBoxLayout()
        self.vertical_layout_1.setObjectName("vertical_layout_1")
        self.label_picture_1 = QtWidgets.QLabel(manual_attendance)
        self.label_picture_1.setText("")
        self.label_picture_1.setPixmap(QtGui.QPixmap("assets/user.png"))
        self.label_picture_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_picture_1.setObjectName("label_picture_1")
        self.vertical_layout_1.addWidget(self.label_picture_1, 0, QtCore.Qt.AlignHCenter)
        self.checkbox_1 = QtWidgets.QCheckBox(manual_attendance)
        self.checkbox_1.setIconSize(QtCore.QSize(64, 64))
        self.checkbox_1.setObjectName("checkbox_1")
        self.vertical_layout_1.addWidget(self.checkbox_1, 0, QtCore.Qt.AlignHCenter)
        self.label_1 = QtWidgets.QLabel(manual_attendance)
        self.label_1.setObjectName("label_1")
        self.vertical_layout_1.addWidget(self.label_1, 0, QtCore.Qt.AlignHCenter)
        self.grid_layout_2.addLayout(self.vertical_layout_1, 0, 0, 1, 1)
        self.vertical_layout_5 = QtWidgets.QVBoxLayout()
        self.vertical_layout_5.setObjectName("vertical_layout_5")
        self.label_picture_5 = QtWidgets.QLabel(manual_attendance)
        self.label_picture_5.setText("")
        self.label_picture_5.setPixmap(QtGui.QPixmap("assets/user.png"))
        self.label_picture_5.setObjectName("label_picture_5")
        self.vertical_layout_5.addWidget(self.label_picture_5, 0, QtCore.Qt.AlignHCenter)
        self.checkbox_5 = QtWidgets.QCheckBox(manual_attendance)
        self.checkbox_5.setIconSize(QtCore.QSize(64, 64))
        self.checkbox_5.setObjectName("checkbox_5")
        self.vertical_layout_5.addWidget(self.checkbox_5, 0, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(manual_attendance)
        self.label_5.setObjectName("label_5")
        self.vertical_layout_5.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.grid_layout_2.addLayout(self.vertical_layout_5, 0, 8, 1, 1)
        self.v_line_4 = QtWidgets.QFrame(manual_attendance)
        self.v_line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line_4.setObjectName("v_line_4")
        self.grid_layout_2.addWidget(self.v_line_4, 0, 7, 1, 1)
        self.h_line_1 = QtWidgets.QFrame(manual_attendance)
        self.h_line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.h_line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.h_line_1.setObjectName("h_line_1")
        self.grid_layout_2.addWidget(self.h_line_1, 1, 0, 1, 1)
        self.vertical_layout_10 = QtWidgets.QVBoxLayout()
        self.vertical_layout_10.setObjectName("vertical_layout_10")
        self.label_picture_10 = QtWidgets.QLabel(manual_attendance)
        self.label_picture_10.setText("")
        self.label_picture_10.setPixmap(QtGui.QPixmap("assets/user.png"))
        self.label_picture_10.setObjectName("label_picture_10")
        self.vertical_layout_10.addWidget(self.label_picture_10, 0, QtCore.Qt.AlignHCenter)
        self.checkbox_10 = QtWidgets.QCheckBox(manual_attendance)
        self.checkbox_10.setIconSize(QtCore.QSize(64, 64))
        self.checkbox_10.setObjectName("checkbox_10")
        self.vertical_layout_10.addWidget(self.checkbox_10, 0, QtCore.Qt.AlignHCenter)
        self.label_10 = QtWidgets.QLabel(manual_attendance)
        self.label_10.setObjectName("label_10")
        self.vertical_layout_10.addWidget(self.label_10, 0, QtCore.Qt.AlignHCenter)
        self.grid_layout_2.addLayout(self.vertical_layout_10, 2, 8, 1, 1)
        self.vertical_layout_4 = QtWidgets.QVBoxLayout()
        self.vertical_layout_4.setObjectName("vertical_layout_4")
        self.label_picture_4 = QtWidgets.QLabel(manual_attendance)
        self.label_picture_4.setText("")
        self.label_picture_4.setPixmap(QtGui.QPixmap("assets/user.png"))
        self.label_picture_4.setObjectName("label_picture_4")
        self.vertical_layout_4.addWidget(self.label_picture_4, 0, QtCore.Qt.AlignHCenter)
        self.checkbox_4 = QtWidgets.QCheckBox(manual_attendance)
        self.checkbox_4.setIconSize(QtCore.QSize(64, 64))
        self.checkbox_4.setObjectName("checkbox_4")
        self.vertical_layout_4.addWidget(self.checkbox_4, 0, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(manual_attendance)
        self.label_4.setObjectName("label_4")
        self.vertical_layout_4.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.grid_layout_2.addLayout(self.vertical_layout_4, 0, 6, 1, 1)
        self.v_line_1 = QtWidgets.QFrame(manual_attendance)
        self.v_line_1.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line_1.setObjectName("v_line_1")
        self.grid_layout_2.addWidget(self.v_line_1, 0, 1, 1, 1)
        self.vertical_layout_9 = QtWidgets.QVBoxLayout()
        self.vertical_layout_9.setObjectName("vertical_layout_9")
        self.label_picture_9 = QtWidgets.QLabel(manual_attendance)
        self.label_picture_9.setText("")
        self.label_picture_9.setPixmap(QtGui.QPixmap("assets/user.png"))
        self.label_picture_9.setObjectName("label_picture_9")
        self.vertical_layout_9.addWidget(self.label_picture_9, 0, QtCore.Qt.AlignHCenter)
        self.checkbox_9 = QtWidgets.QCheckBox(manual_attendance)
        self.checkbox_9.setIconSize(QtCore.QSize(64, 64))
        self.checkbox_9.setObjectName("checkbox_9")
        self.vertical_layout_9.addWidget(self.checkbox_9, 0, QtCore.Qt.AlignHCenter)
        self.label_9 = QtWidgets.QLabel(manual_attendance)
        self.label_9.setObjectName("label_9")
        self.vertical_layout_9.addWidget(self.label_9, 0, QtCore.Qt.AlignHCenter)
        self.grid_layout_2.addLayout(self.vertical_layout_9, 2, 6, 1, 1)
        self.v_line_5 = QtWidgets.QFrame(manual_attendance)
        self.v_line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line_5.setObjectName("v_line_5")
        self.grid_layout_2.addWidget(self.v_line_5, 2, 1, 1, 1)
        self.vertical_layout_6 = QtWidgets.QVBoxLayout()
        self.vertical_layout_6.setObjectName("vertical_layout_6")
        self.label_picture_6 = QtWidgets.QLabel(manual_attendance)
        self.label_picture_6.setText("")
        self.label_picture_6.setPixmap(QtGui.QPixmap("assets/user.png"))
        self.label_picture_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_picture_6.setObjectName("label_picture_6")
        self.vertical_layout_6.addWidget(self.label_picture_6, 0, QtCore.Qt.AlignHCenter)
        self.checkbox_6 = QtWidgets.QCheckBox(manual_attendance)
        self.checkbox_6.setIconSize(QtCore.QSize(64, 64))
        self.checkbox_6.setObjectName("checkbox_6")
        self.vertical_layout_6.addWidget(self.checkbox_6, 0, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(manual_attendance)
        self.label_6.setObjectName("label_6")
        self.vertical_layout_6.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        self.grid_layout_2.addLayout(self.vertical_layout_6, 2, 0, 1, 1)
        self.v_line_7 = QtWidgets.QFrame(manual_attendance)
        self.v_line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line_7.setObjectName("v_line_7")
        self.grid_layout_2.addWidget(self.v_line_7, 2, 5, 1, 1)
        self.v_line_3 = QtWidgets.QFrame(manual_attendance)
        self.v_line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line_3.setObjectName("v_line_3")
        self.grid_layout_2.addWidget(self.v_line_3, 0, 5, 1, 1)
        self.v_line_6 = QtWidgets.QFrame(manual_attendance)
        self.v_line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line_6.setObjectName("v_line_6")
        self.grid_layout_2.addWidget(self.v_line_6, 2, 3, 1, 1)
        self.v_line_2 = QtWidgets.QFrame(manual_attendance)
        self.v_line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line_2.setObjectName("v_line_2")
        self.grid_layout_2.addWidget(self.v_line_2, 0, 3, 1, 1)
        self.v_line_8 = QtWidgets.QFrame(manual_attendance)
        self.v_line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line_8.setObjectName("v_line_8")
        self.grid_layout_2.addWidget(self.v_line_8, 2, 7, 1, 1)
        self.h_line_2 = QtWidgets.QFrame(manual_attendance)
        self.h_line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.h_line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.h_line_2.setObjectName("h_line_2")
        self.grid_layout_2.addWidget(self.h_line_2, 1, 2, 1, 1)
        self.h_line_3 = QtWidgets.QFrame(manual_attendance)
        self.h_line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.h_line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.h_line_3.setObjectName("h_line_3")
        self.grid_layout_2.addWidget(self.h_line_3, 1, 4, 1, 1)
        self.h_line_4 = QtWidgets.QFrame(manual_attendance)
        self.h_line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.h_line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.h_line_4.setObjectName("h_line_4")
        self.grid_layout_2.addWidget(self.h_line_4, 1, 6, 1, 1)
        self.h_line_5 = QtWidgets.QFrame(manual_attendance)
        self.h_line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.h_line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.h_line_5.setObjectName("h_line_5")
        self.grid_layout_2.addWidget(self.h_line_5, 1, 8, 1, 1)
        self.grid_layout.addLayout(self.grid_layout_2, 10, 0, 2, 3)
        self.button_update = QtWidgets.QPushButton(manual_attendance)
        self.button_update.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/tick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_update.setIcon(icon2)
        self.button_update.setIconSize(QtCore.QSize(32, 32))
        self.button_update.setFlat(False)
        self.button_update.setObjectName("button_update")
        self.grid_layout.addWidget(self.button_update, 13, 0, 1, 3, QtCore.Qt.AlignHCenter)
        self.label_update_icon = QtWidgets.QLabel(manual_attendance)
        self.label_update_icon.setText("")
        self.label_update_icon.setPixmap(QtGui.QPixmap("assets/file.png"))
        self.label_update_icon.setScaledContents(True)
        self.label_update_icon.setObjectName("label_update_icon")
        self.grid_layout.addWidget(self.label_update_icon, 8, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_placeholder = QtWidgets.QLabel(manual_attendance)
        self.label_placeholder.setObjectName("label_placeholder")
        self.grid_layout.addWidget(self.label_placeholder, 9, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)

        self.retranslateUi(manual_attendance)
        QtCore.QMetaObject.connectSlotsByName(manual_attendance)
        manual_attendance.setTabOrder(self.checkbox_1, self.checkbox_2)
        manual_attendance.setTabOrder(self.checkbox_2, self.checkbox_3)
        manual_attendance.setTabOrder(self.checkbox_3, self.checkbox_4)
        manual_attendance.setTabOrder(self.checkbox_4, self.checkbox_5)
        manual_attendance.setTabOrder(self.checkbox_5, self.checkbox_6)
        manual_attendance.setTabOrder(self.checkbox_6, self.checkbox_7)
        manual_attendance.setTabOrder(self.checkbox_7, self.checkbox_8)
        manual_attendance.setTabOrder(self.checkbox_8, self.checkbox_9)
        manual_attendance.setTabOrder(self.checkbox_9, self.checkbox_10)
        manual_attendance.setTabOrder(self.checkbox_10, self.button_update)
        manual_attendance.setTabOrder(self.button_update, self.button_back)

    def retranslateUi(self, manual_attendance):
        _translate = QtCore.QCoreApplication.translate
        manual_attendance.setWindowTitle(_translate("manual_attendance", "Manual Attendance"))
        self.label_manual_attendance.setText(_translate("manual_attendance", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#888a85;\">MANUAL ATTENDANCE</span></p></body></html>"))
        self.checkbox_3.setText(_translate("manual_attendance", "CheckBox"))
        self.label_3.setText(_translate("manual_attendance", "TextLabel"))
        self.checkbox_8.setText(_translate("manual_attendance", "CheckBox"))
        self.label_8.setText(_translate("manual_attendance", "TextLabel"))
        self.checkbox_2.setText(_translate("manual_attendance", "CheckBox"))
        self.label_2.setText(_translate("manual_attendance", "TextLabel"))
        self.checkbox_7.setText(_translate("manual_attendance", "CheckBox"))
        self.label_7.setText(_translate("manual_attendance", "TextLabel"))
        self.checkbox_1.setText(_translate("manual_attendance", "CheckBox"))
        self.label_1.setText(_translate("manual_attendance", "TextLabel"))
        self.checkbox_5.setText(_translate("manual_attendance", "CheckBox"))
        self.label_5.setText(_translate("manual_attendance", "TextLabel"))
        self.checkbox_10.setText(_translate("manual_attendance", "CheckBox"))
        self.label_10.setText(_translate("manual_attendance", "TextLabel"))
        self.checkbox_4.setText(_translate("manual_attendance", "CheckBox"))
        self.label_4.setText(_translate("manual_attendance", "TextLabel"))
        self.checkbox_9.setText(_translate("manual_attendance", "CheckBox"))
        self.label_9.setText(_translate("manual_attendance", "TextLabel"))
        self.checkbox_6.setText(_translate("manual_attendance", "CheckBox"))
        self.label_6.setText(_translate("manual_attendance", "TextLabel"))
        self.label_placeholder.setText(_translate("manual_attendance", "Check or uncheck the boxes to change the status of the attendance record of the student:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    manual_attendance = QtWidgets.QWidget()
    ui = Ui_manual_attendance()
    ui.setupUi(manual_attendance)
    manual_attendance.show()
    sys.exit(app.exec_())
