from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form_login(object):
    def setupUi(self, form_login):
        form_login.setObjectName("form_login")
        form_login.resize(380, 430)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/FaceAttend2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        form_login.setWindowIcon(icon)
        self.gridLayout_3 = QtWidgets.QGridLayout(form_login)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.button_signup = QtWidgets.QPushButton(form_login)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/key.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_signup.setIcon(icon1)
        self.button_signup.setObjectName("button_signup")
        self.verticalLayout_2.addWidget(self.button_signup)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 9, 0, 1, 1)
        self.label_faceattend_icon = QtWidgets.QLabel(form_login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_faceattend_icon.sizePolicy().hasHeightForWidth())
        self.label_faceattend_icon.setSizePolicy(sizePolicy)
        self.label_faceattend_icon.setMinimumSize(QtCore.QSize(1, 1))
        self.label_faceattend_icon.setBaseSize(QtCore.QSize(0, 0))
        self.label_faceattend_icon.setText("")
        self.label_faceattend_icon.setPixmap(QtGui.QPixmap("assets/FaceAttend2.png"))
        self.label_faceattend_icon.setObjectName("label_faceattend_icon")
        self.gridLayout_3.addWidget(self.label_faceattend_icon, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_spacer_bottom = QtWidgets.QLabel(form_login)
        self.label_spacer_bottom.setText("")
        self.label_spacer_bottom.setAlignment(QtCore.Qt.AlignCenter)
        self.label_spacer_bottom.setObjectName("label_spacer_bottom")
        self.gridLayout_3.addWidget(self.label_spacer_bottom, 2, 0, 1, 1)
        self.line_edit_password = QtWidgets.QLineEdit(form_login)
        self.line_edit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_edit_password.setAlignment(QtCore.Qt.AlignCenter)
        self.line_edit_password.setClearButtonEnabled(True)
        self.line_edit_password.setObjectName("line_edit_password")
        self.gridLayout_3.addWidget(self.line_edit_password, 6, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_spacer_top = QtWidgets.QLabel(form_login)
        self.label_spacer_top.setText("")
        self.label_spacer_top.setObjectName("label_spacer_top")
        self.gridLayout.addWidget(self.label_spacer_top, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.line_edit_cpassword = QtWidgets.QLineEdit(form_login)
        self.line_edit_cpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_edit_cpassword.setAlignment(QtCore.Qt.AlignCenter)
        self.line_edit_cpassword.setClearButtonEnabled(True)
        self.line_edit_cpassword.setObjectName("line_edit_cpassword")
        self.gridLayout_3.addWidget(self.line_edit_cpassword, 7, 0, 1, 1)
        self.line_edit_username = QtWidgets.QLineEdit(form_login)
        self.line_edit_username.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_edit_username.setAlignment(QtCore.Qt.AlignCenter)
        self.line_edit_username.setClearButtonEnabled(True)
        self.line_edit_username.setObjectName("line_edit_username")
        self.gridLayout_3.addWidget(self.line_edit_username, 5, 0, 1, 1)
        self.line_edit_contact_number = QtWidgets.QLineEdit(form_login)
        self.line_edit_contact_number.setAlignment(QtCore.Qt.AlignCenter)
        self.line_edit_contact_number.setClearButtonEnabled(True)
        self.line_edit_contact_number.setObjectName("line_edit_contact_number")
        self.gridLayout_3.addWidget(self.line_edit_contact_number, 4, 0, 1, 1)
        self.line_edit_fullname = QtWidgets.QLineEdit(form_login)
        self.line_edit_fullname.setAlignment(QtCore.Qt.AlignCenter)
        self.line_edit_fullname.setClearButtonEnabled(True)
        self.line_edit_fullname.setObjectName("line_edit_fullname")
        self.gridLayout_3.addWidget(self.line_edit_fullname, 3, 0, 1, 1)

        self.retranslateUi(form_login)
        QtCore.QMetaObject.connectSlotsByName(form_login)
        form_login.setTabOrder(self.line_edit_fullname, self.line_edit_contact_number)
        form_login.setTabOrder(self.line_edit_contact_number, self.line_edit_username)
        form_login.setTabOrder(self.line_edit_username, self.line_edit_password)
        form_login.setTabOrder(self.line_edit_password, self.line_edit_cpassword)
        form_login.setTabOrder(self.line_edit_cpassword, self.button_signup)

    def retranslateUi(self, form_login):
        _translate = QtCore.QCoreApplication.translate
        form_login.setWindowTitle(_translate("form_login", "Signup"))
        self.button_signup.setText(_translate("form_login", "Signup"))
        self.line_edit_password.setPlaceholderText(_translate("form_login", "Password"))
        self.line_edit_cpassword.setPlaceholderText(_translate("form_login", "Confirm Password"))
        self.line_edit_username.setPlaceholderText(_translate("form_login", "Username"))
        self.line_edit_contact_number.setPlaceholderText(_translate("form_login", "Contact Number"))
        self.line_edit_fullname.setPlaceholderText(_translate("form_login", "Full Name"))

    def siginWindow(self):
        ajkdjkafbjb
        asbhdbahsbd


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form_login = QtWidgets.QWidget()
    ui = Ui_form_login()
    ui.setupUi(form_login)
    form_login.show()
    sys.exit(app.exec_())
